containerRegistry: gcr.io/origin-214503

clusterIssuer: letsencrypt-prod

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: latest
bridgeReplicas: 2

# origin-dapp
dappImage: origin-dapp
dappImageTag: latest
dappReplicas: 2

# ipfs
ipfsImage: ipfs/go-ipfs
ipfsImageTag: master

# origin-messaging-ipfs
messagingIpfsImage: ipfs/go-ipfs
# See https://github.com/libp2p/go-floodsub/issues/93
messagingIpfsImageTag: v0.4.17

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: latest

# geth private node bootnode
bootnodeImage: ethereum/client-go
bootnodeImageTag: alltools-v1.8.13

# ethstats for geth nodes
ethstatsImage: ethereumex/eth-stats-dashboard
ethstatsImageTag: latest

gethImage: ethereum/client-go
gethImageTag: v1.8.13
gethTxReplicas: 1
gethMinerReplicas: 2
gethMinerCpuLimit: 0.5

gethGenesisNetworkId: 2222
gethGenesisDifficulty: '0x400'
gethGenesisGasLimit: '0x8000000'

gethAccountAddress: 0xee3b32485b5d9eee1e3ceb1ad2e2ea1493192d2d
gethAccountPublicKey: f1afaa4f22dedc95df4023300ccd64456809624e70d321542ee0af8756c332b8934c362dc54ea37ec327d08b61faa55d428e86f84cfc1e3d08bfbae15ff37327
