apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address for use with LetsEncrypt
    email: tlinton@dockyard.nz
    privateKeySecretRef:
      name: letsencrypt-clusterissuer
    http01: {}
