version: '3'
services:
  origin:
    container_name: "origin-container"
    image: origin-image
    build: ./container
    volumes:
      - ./origin-bridge:/opt/origin-bridge/source
      - ./origin-js:/opt/origin-js/source
      - /opt/origin-js/source/node_modules
      - ./origin-dapp:/opt/origin-dapp/source
      - /opt/origin-dapp/source/node_modules
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
      - "5002:5002"
      - "5432:5432"
      - "6379:6379"
      - "8080:8080"
      - "8081:8081"
      - "8545:8545"
      - "9200:9200"
