version: "3"

networks:
  origin-ipfs:
  origin-messaging-ipfs:
  origin-box:

volumes:
  origin_js_node_modules:
  contracts:  # Compiled contracts
  flask_session: # Flask session persistence
  pg_data:

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10.0
    # Data persistence, comment out the following two lines to disable
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=origin
      - POSTGRES_PASSWORD=origin
      - POSTGRES_DB=origin_bridge
    networks:
      - origin-box

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    build:
      context: .
      dockerfile: containers/dockerfiles/development/elasticsearch
    ports:
      - "9200:9200"
    environment:
      network.bind_host: 0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9200:9200"
    networks:
      - origin-box

  origin-js:
    container_name: origin-js
    image: origin-js
    build:
      context: .
      dockerfile: containers/dockerfiles/development/origin-js
    volumes:
      - ./origin-js:/app
      - origin_js_node_modules:/app/node_modules
      - contracts:/app/contracts/build/contracts
    environment:
      - NODE_ENV=development
    ports:
      # - "5002:5002" # API
      # - "8080:8080" # IPFS gateway
      - "8081:8081" # Tests
      - "8545:8545" # Blockchain
      - "4000:4000" # Apollo server
    # Run npm install on every container start to avoid volumes issue
    # https://github.com/docker/compose/issues/4337
    command: >
      /bin/bash -c "npm install --quiet --no-progress &&
      node scripts/build.js serve"
    networks:
      - origin-box

  origin-messaging-ipfs:
    container_name: origin-messaging-ipfs
    image: ipfs/go-ipfs:latest
    networks:
      - origin-messaging-ipfs
    ports:
      - "5002:5002"
      - "8080:8080"
    environment:
      - IPFS_PATH=/ipfs
    volumes:
      - ./containers/.ipfs:/ipfs
    command: "daemon --enable-pubsub-experiment"

  origin-messaging:
    container_name: origin-messaging
    build:
      context: .
      dockerfile: containers/dockerfiles/development/origin-messaging
    image: origin-messaging
    depends_on:
      - origin-messaging-ipfs
    networks:
      - origin-messaging-ipfs
      - origin-box
    ports:
      - "9012:9012"
    volumes:
      - ./origin-messaging/src:/app/src
    environment:
      - IPFS_ADDRESS=origin-messaging-ipfs
      - MESSAGING_NAMESPACE=dev
    # TODO Add nodemon
    # Waits for origin-messaging-ipfs to be available before starting
    command: /bin/bash -c "wait-for.sh -t 0 -q origin-messaging-ipfs:5001 --
      node_modules/.bin/babel-node src/index.js --presets es2015"

  origin-bridge:
    container_name: origin-bridge
    build:
      context: .
      dockerfile: containers/dockerfiles/development/origin-bridge
    image: origin-bridge
    volumes:
      - ./origin-bridge:/app
      # Set the envfile from the local envfile
      - ./containers/envfiles/origin-bridge.env:/app/.env
      - flask_session:/app/flask_session
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    networks:
      - origin-box

  origin-dapp:
    container_name: origin-dapp
    build:
      context: .
      dockerfile: containers/dockerfiles/development/origin-dapp
    volumes:
      # Mount origin-dapp inside the container
      - ./origin-dapp:/app
      # Set the envfile from the local envfile
      - ./containers/envfiles/origin-dapp.env:/app/.env
      # Mount compiled origin-js inside node modules
      - ./origin-js:/usr/local/lib/node_modules/origin
      - origin_js_node_modules:/usr/local/lib/node_modules/origin/node_modules
      - ./ipfs/repo:/app/ipfsrepo
    depends_on:
      - origin-messaging
      - origin-bridge
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command:
      # Waits for origin-js and origin-messaging-ipfs to start then uses a
      # script to read the origin-messaging-ipfs container peer id and write the
      # configuration key/pair to the .env file.
      #
      # The copying is necessary because the .env file is mounted as a volume
      # and the inode is not allowed to change.
      >
      /bin/bash -c "wait-for.sh -t 0 -q origin-js:8081 --
      cp /app/.env /tmp/.env.new &&
      set-ipfs-swarm.sh /ipfs/config /tmp/.env.new &&
      cp /tmp/.env.new /app/.env &&
      npm install --quiet --no-progress &&
      npm link origin &&
      node_modules/.bin/webpack-dev-server --host 0.0.0.0 --watch-poll 500"
    networks:
      - origin-ipfs
      - origin-box
