version: "3"

networks:
  origin-develop:

volumes:
  origin_js_node_modules:
  contracts:  # Compiled contracts
  flask_session: # Flask session persistence
  pg_data:

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10.0
    # Data persistence, comment out the following two lines to disable
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=origin
      - POSTGRES_PASSWORD=origin
      - POSTGRES_DB=origin_bridge
    networks:
      - origin-develop

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    build:
      context: .
      dockerfile: dockerfiles/elasticsearch
    ports:
      - "9200:9200"
    environment:
      network.bind_host: 0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9200:9200"
    networks:
      - origin-develop

  origin-js:
    container_name: origin-js
    image: origin-js
    build:
      context: .
      dockerfile: dockerfiles/origin-js
    volumes:
      - ./origin-js:/app
      - origin_js_node_modules:/app/node_modules
      - contracts:/app/contracts/build/contracts
    environment:
      - NODE_ENV=development
    ports:
      - "5002:5002" # API
      - "8080:8080" # IPFS gateway
      - "8081:8081" # Tests
      - "8545:8545" # Blockchain
      - "4000:4000" # Apollo server
    # Run npm install on every container start to avoid volumes issue
    # https://github.com/docker/compose/issues/4337
    command: >
      /bin/bash -c "npm install --quiet --no-progress &&
      node scripts/build.js serve"
    networks:
      - origin-develop

  orbit-db:
    container_name: orbit-db
    build:
      context: .
      dockerfile: dockerfiles/orbit-db
    image: orbit-db
    volumes:
      - ./origin-bridge/js/messaging:/app/messaging
      - ./ipfs/repo:/app/ipfsrepo
    ports:
      - "9012:9012"
    environment:
      - MESSAGING_IPFS_WS_ADDRESS=/ip4/0.0.0.0/tcp/9012/ws
      - MESSAGING_NAMESPACE=dev
    command: node_modules/.bin/babel-node messaging/orbit_server.js --presets es2015
    networks:
      - origin-develop

  origin-bridge:
    container_name: origin-bridge
    build:
      context: .
      dockerfile: dockerfiles/origin-bridge
    image: origin-bridge
    volumes:
      - ./origin-bridge:/app
      # Set the envfile from the local envfile
      - ./envfiles/origin-bridge.env:/app/.env
      - flask_session:/app/flask_session
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    networks:
      - origin-develop

  origin-dapp:
    container_name: origin-dapp
    build:
      context: .
      dockerfile: dockerfiles/origin-dapp
    volumes:
      # Mount origin-dapp inside the container
      - ./origin-dapp:/app
      # Set the envfile from the local envfile
      - ./envfiles/origin-dapp.env:/app/.env
      # Mount compiled origin-js inside node modules
      - ./origin-js:/usr/local/lib/node_modules/origin
      - origin_js_node_modules:/usr/local/lib/node_modules/origin/node_modules
      - ./ipfs/repo:/app/ipfsrepo
    depends_on:
      - orbit-db
      - origin-bridge
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command:
      # Waits for origin-js and orbit-db to start then uses a script to read the
      # orbit-db container peer id and write the configuration key/pair to the
      # .env file.
      #
      # The copying is necessary because the .env file is mounted as a volume
      # and the inode is not allowed to change.
      >
      /bin/bash -c "wait-for.sh -t 0 -q origin-js:8081 --
      cp /app/.env /tmp/.env.new &&
      set-ipfs-swarm.sh /app/ipfsrepo/config /tmp/.env.new &&
      cp /tmp/.env.new /app/.env &&
      npm install --quiet --no-progress &&
      npm link origin &&
      node_modules/.bin/webpack-dev-server --host 0.0.0.0 --watch-poll 500"
    networks:
      - origin-develop
