apiVersion: v1
kind: Service
metadata:
  name: {{ template "dapp.fullname" . }}
  labels:
    app: {{ template "dapp.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "dapp.fullname" . }}
  ports:
  - name: nginx
    port: 80
    protocol: TCP
