{{- if eq .Release.Namespace "dev" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ethereum.fullname" . }}-account
  labels:
    app: {{ template "ethereum.fullname" . }}-account
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  accountPrivateKey: {{ required ".Values.gethAccountPrivateKey required" .Values.gethAccountPrivateKey | b64enc | quote }}
  accountSecret: {{ required ".Values.gethAccountSecret required" .Values.gethAccountSecret | b64enc | quote }}
{{- end }}
