# Enable discovery of Ethereum nodes
# This is only desirable for real Ethereum testnets or mainnet, we don't want
# our private network to be discoverable

{{ if ne ".Release.Namespace" "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ethereum.fullname" . }}-discovery
  labels:
    app: {{ template "ethereum.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  selector:
    app: {{ template "ethereum.fullname" . }}-tx-node
  ports:
  - name: discovery-udp
    port: 30303
    protocol: UDP
{{ end }}
