{{ if ne .Release.Namespace "prod" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "faucet.fullname" . }}
  labels:
    app: {{ template "faucet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - secretName: faucet.{{ .Release.Namespace }}.originprotocol.com
      hosts:
        - faucet.{{ .Release.Namespace }}.originprotocol.com
  rules:
  - host: faucet.{{ .Release.Namespace }}.originprotocol.com
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "faucet.fullname" . }}
            servicePort: 5000
{{ end }}
