bridgeEnvKey: ENC[AES256_GCM,data:MsZijA4EyK5tDjyHx5Sd/D71kndMWHxVrdo8aA8pIxiDSKb2hw==,iv:LRls+8iq0kPtXgC+YmA9s3Gv032LpCkig3yow2hhYZ0=,tag:OdkX7ieCsw2FzUJuS/LoKg==,type:str]
#ENC[AES256_GCM,data:CnQoQv3Ozb9IJY7FD/8MdjOW+mzmDqAxFzdHR0Qjs4eVBbL3P1vBlHJj+jY+h3bL3N13MULz9+PS,iv:wowguvbitKdMaT/YBhXg8+AB/jgSrPGKxGgREew5BaM=,tag:nd8e8vDGtX0jtgXCrfyLPA==,type:comment]
ethstatsWebsocketSecret: ENC[AES256_GCM,data:cN9JvUAPuxYjVf74SPOu+Q==,iv:pxA784v40U6rn126SeQcLqvq6o4lvtRVsIrbrX3hc78=,tag:3qaPuTsLTBxz04KkCqLECA==,type:str]
#ENC[AES256_GCM,data:6oJtDjk0VCkydwh7YrdimSHqPvv3zw1Ohtv3rl529eUc,iv:ElThgKkAu6nLEvcpzzF1+OvSJxldFxlYv+85xymhh8U=,tag:YqHQ7hIuNM2iJQDTSqkhZQ==,type:comment]
databaseUsername: ENC[AES256_GCM,data:EthZldz7,iv:KTngLdsnSNWVZww8s2cprc8giCzmqwfJZln8cua1GCI=,tag:WyKPHzrnB0UuDBRzAF8Mlg==,type:str]
databasePassword: ENC[AES256_GCM,data:yUFRCyPgC3vcuMitiqCG+A==,iv:yuyPZr+INZQtpOR5A4sXEAlvzA34V1qU/yOwTUO6rNw=,tag:FIRtYKOrHc7khEfxuZ/QdA==,type:str]
#ENC[AES256_GCM,data:aB0ebEV4zY04609kypCnOBpCtE8IWaDzaATsXcqUOg==,iv:jFSsLLAn1IvNxxYPIU0d38lTsTo3R0cXlpVkxiRpAhg=,tag:OFp0mcy0tTIo72VeQmSkXg==,type:comment]
infuraAccessToken: ENC[AES256_GCM,data:nbs0q+7/hY3mU4CJx2IZmxXyVng=,iv:X7aeEqQUTPnctnWRCmPgwr3UM/QauRqK6S7ID7jgFQ8=,tag:+qH6O8oDxwgof/rF0QjOVA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/origin-214503/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2018-09-28T09:32:41Z'
        enc: CiQAJ0Lg+0Q1h1l/0z7WF346Lw7f9+8HGq/yZT4tsqhRsp5DT7MSSQA4BiSnm9CW/DMPGcxloSdNEAZPvSQYAd06yUdaxm39vhuV+E29LhjrZ0C9IofNmuji3czcqVZMxFqrpSmgqpPfSoRoT2ZaFXM=
    lastmodified: '2018-09-28T09:32:42Z'
    mac: ENC[AES256_GCM,data:gBn0+Lt1MDUOXq2oAlzdDkuwj/0w3k0jrwfZR2YOL6jtWEkz8ogAkQGw4JvHMF4c758VUh0F+noabeuood8otUmakNpJR3HZ9a1vzSYXO2Wbap8e/vFqK8/8PZcgtN8ahouGHa2wsgkM1X5MvfOyxOeDFm+2AvRDz5E2+tvVQGk=,iv:3EBu6u8yp+YP6H6BoLMlutnSUScDlf9ENbjIoxGy9YE=,tag:GlDcXu0fOtaGjjwmnVtnoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.0.5
