databaseInstance: origin-214503:us-west1:prod

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '32de267'
bridgeReplicas: 1

# origin-dapp
dappImage: origin-dapp
dappImageTag: '159f1f0-1538800098'
dappReplicas: 2

# Mainnet nodes
gethTxReplicas: 1

# IPFS server
ipfsImageTag: ipfs/go-ipfs
ipfsImageTag: master

faucetImage: origin-faucet
faucetImageTag: '28438d2'

eventlistenerImage: event-listener
eventlistenerImageTag: '6e22b35-1538544696'
eventlistenerWeb3Url: https://mainnet.infura.io/emIXjs9eDuy57IlTYsIP
eventlistenerContinueBlock: 6425000

discoveryImage: origin-discovery
discoveryImageTag: '6e22b35'

# IPFS server for OrbitDB
messagingIpfsImage: ipfs/go-ipfs
messagingIpfsImageTag: v0.4.17

# OrbitDB
messagingImage: origin-messaging
messagingImageTag: '3104d23'
