# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '2062a05'
bridgeReplicas: 1

# origin-dapp
dappImage: origin-dapp
dappImageTag: '5498d6d-1537941958'
dappReplicas: 2

# Rinkeby network configuration
gethTxReplicas: 1
gethTxMemoryRequest: 6Gi

# IPFS server
ipfsImageTag: ipfs/go-ipfs
ipfsImageTag: master

faucetImage: origin-faucet
faucetImageTag: '55ef75b'

eventlistenerImage: event-listener
eventlistenerImageTag: '55ef75b'
eventlistenerWeb3Url: https://rinkeby.infura.io/emIXjs9eDuy57IlTYsIP
eventlistenerContinueBlock: 3000000

discoveryImage: origin-discovery
discoveryDbInstance: origin-214503:us-west1:staging
discoveryImageTag: '1cfc84d'

# IPFS server for OrbitDB
messagingIpfsImage: ipfs/go-ipfs
messagingIpfsImageTag: v0.4.17

# OrbitDB
messagingImage: origin-messaging
messagingImageTag: 'a444ac1'
