# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: latest
bridgeReplicas: 2

# origin-dapp
dappImage: origin-dapp
dappImageTag: 'latest'
dappReplicas: 2

# Rinkeby network congiruation
gethTxReplicas: 1

# IPFS server
ipfsImageTag: ipfs/go-ipfs
ipfsImageTag: master

faucetImageTag: '28438d2'

# IPFS server for OrbitDB
messagingIpfsImage: ipfs/go-ipfs
messagingIpfsImageTag: v0.4.17
#
# OrbitDB
messagingImage: origin-messaging
messagingImageTag: 'latest'
