databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: 'cc2e4a7'
bridgeReplicas: 1

# origin-dapp
dappImage: origin-dapp
dappImageTag: '843e5fe'
dappReplicas: 2

# Origin network configuration
gethTxReplicas: 1
gethMinerReplicas: 2
gethMinerCpuLimit: 0.5

# IPFS server
ipfsImageTag: ipfs/go-ipfs
ipfsImageTag: master

faucetImage: origin-faucet
faucetImageTag: '28438d2'

eventlistenerImage: event-listener
eventlistenerImageTag: '2b21d78'
eventlistenerWeb3Url: https://eth.dev.originprotocol.com/rpc

discoveryImage: origin-discovery
discoveryImageTag: '2b21d78'

# IPFS server for OrbitDB
messagingIpfsImage: ipfs/go-ipfs
messagingIpfsImageTag: v0.4.17

# OrbitDB
messagingImage: origin-messaging
messagingImageTag: 'a444ac1'
