apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bridge.fullname" . }}
  labels:
    app: {{ template "bridge.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ENVKEY: {{ required "Set a .Values.bridgeEnvKey" .Values.bridgeEnvKey | b64enc | quote}}
  DATABASE_USERNAME: {{ required ".Values.databaseUsername required" .Values.databaseUsername | b64enc | quote }}
  DATABASE_PASSWORD: {{ required ".Values.databasePassword required" .Values.databasePassword | b64enc | quote }}
