apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dapp.fullname" . }}
  labels:
    app: {{ template "dapp.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ default 2 .Values.dappReplicas }}
  selector:
    matchLabels:
      app: {{ template "dapp.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "dapp.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: origin-dapp
        image: "{{ .Values.containerRegistry }}/{{ .Release.Namespace }}/{{ .Values.dappImage }}:{{ .Values.dappImageTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
