# Bootnode is used for private Ethereum blockchain
# It only gets installed in the dev namespace

{{- if eq .Release.Namespace "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ethereum.fullname" . }}-bootnode
  labels:
    app: {{ template "ethereum.fullname" . }}-bootnode
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "ethereum.fullname" . }}-bootnode
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: 80
  - name: discovery
    port: 30301
    protocol: UDP
{{- end }}
