apiVersion: v1
kind: Service
metadata:
metadata:
  name: {{ template "bridge.fullname" . }}
  labels:
    app: {{ template "bridge.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "bridge.fullname" . }}
  ports:
  - name: gunicorn
    port: 5000
    protocol: TCP
