# This deployment is for a geth miner for the Origin test blockchain.
{{- if eq .Release.Namespace "dev" }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "eth.fullname" . }}-miner-node
  labels:
    app: {{ template "eth.fullname" . }}-miner-node
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.gethMinerReplicas }}
  selector:
    matchLabels:
      app: {{ template "eth.fullname" . }}-miner-node
  template:
    metadata:
      labels:
        app: {{ template "eth.fullname" . }}-miner-node
    spec:
      containers:
      - name: geth-miner
        image: {{ .Values.gethImage }}:{{ .Values.gethImageTag }}
        args:
        - "--bootnodes=`cat /root/.ethereum/bootnodes`"
        - "--mine"
        - "--etherbase=0"
        - "--networkid=${NETWORK_ID}"
        - "--ethstats=${HOSTNAME}:${ETHSTATS_SECRET}@${ETHSTATS_SERVICE}"
        - "--verbosity=5"
        env:
        - name: ETHSTATS_SERVICE
          value: {{ template "eth.fullname" . }}-ethstats.{{ .Release.Namespace }}.svc.cluster.local
        - name: ETHSTATS_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "eth.fullname" . }}-ethstats
              key: WS_SECRET
        - name: NETWORK_ID
          valueFrom:
            configMapKeyRef:
              name: {{ template "eth.fullname" . }}-config
              key: networkid
        ports:
        - name: discovery-udp
          containerPort: 30303
          protocol: UDP
        - name: discovery-tcp
          containerPort: 30303
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        # Limit the container to a single CPU in the dev environment for mining
        resources:
          limits:
            cpu: "0.25"
      initContainers:
      - name: init-genesis
        image: {{ .Values.gethImage }}:{{ .Values.gethImageTag }}
        args:
          - "init"
          - "/etc/geth/genesis.json"
        volumeMounts:
          - name: data
            mountPath: /root/.ethereum
          - name: genesis-config
            mountPath: /etc/geth/
      {{- if .Values.gethAccountPrivateKey }}
      - name: import-geth-account
        image: {{ .Values.gethImage }}:{{ .Values.gethImageTag }}
        command: ["/bin/sh"]
        args:
        - "-c"
        - "geth account import --password /root/.ethereum/account/accountSecret /root/.ethereum/account/accountPrivateKey"
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: account
          readOnly: true
          mountPath: /root/.ethereum/account
      {{- end }}
      - name: get-bootnodes
        image: {{ .Values.gethImage }}:{{ .Values.gethImageTag }}
        command: ["/bin/sh"]
        args:
        - "-c"
        - |-
{{ .Files.Get "scripts/get-bootnode.sh" | indent 10 }}
        env:
        - name: BOOTNODE_SERVICE
          value: {{ template "eth.fullname" . }}-bootnode.{{ .Release.Namespace }}.svc.cluster.local
        volumeMounts:
        - name: data
          mountPath: /geth
      volumes:
      - name: data
        emptyDir: {}
      - name: genesis-config
        configMap:
          name: {{ template "eth.fullname" . }}-genesis-config
      - name: account
        secret:
          secretName: {{ template "eth.fullname" . }}-account
{{- end }}
