apiVersion: v1
kind: Service
metadata:
  name: {{ template "eth.fullname" . }}
  labels:
    app: {{ template "eth.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "eth.fullname" . }}
  ports:
  - name: rpc
    port: 8545
    protocol: TCP
  - name: ws
    port: 8546
    protocol: TCP
