apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "ipfs.fullname" . }}
  labels:
    app: {{ template "ipfs.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "ipfs.fullname" . }}
  serviceName: {{ template "ipfs.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "ipfs.fullname" . }}
    spec:
      containers:
      - name: {{ template "ipfs.fullname" . }}
        image: "ipfs/go-ipfs:master"
        command: ["/usr/local/bin/start_ipfs"]
        ports:
        - containerPort: 5001
          name: api
          protocol: TCP
        - containerPort: 8080
          name: gateway
          protocol: "TCP"
        volumeMounts:
          - mountPath: /data/ipfs
            name: {{ template "ipfs.fullname" . }}
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: {{ template "ipfs.fullname" . }}
    spec:
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce  # Read-write for a single node only
      resources:
        requests:
          storage: {{ default "8Gi" .Values.ipfsStorageRequestSize }}
