apiVersion: v1
kind: Service
metadata:
  name: {{ template "messaging-ipfs.fullname" . }}
  labels:
    app: {{ template "messaging-ipfs.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - name: api
    port: 5001
    protocol: TCP
  - name: websocket
    port: 9012
    protocol: TCP
  selector:
    app: {{ template "messaging-ipfs.fullname" . }}
