apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auto-gke-pvc-snapshots
spec:
  schedule: {{ .Values.snapshotCron }}
  startingDeadlineSeconds: 10800
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: auto-gke-pvc-snapshots
            image: {{ .Values.snapshotImage }}:{{ .Values.snapshotTag }}
          restartPolicy: OnFailure
