# This pipeline triggers on changes to an origin-dapp branch
#
# It runs tests and then builds and pushes a container to Google
# Container Registry.
#
# TODO Origin-box is used here to provide the same directory structure as the
# monorepo that is being transitioned to.

resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: 9

resources:
- name: origin-box
  type: git
  source:
    uri: https://github.com/OriginProtocol/origin-box
    branch: master
- name: origin-js
  type: git
  source:
    uri: https://github.com/OriginProtocol/origin-js
    branch: ((branch))
- name: origin-dapp
  type: git
  source: &origin-dapp-source
    uri: https://github.com/OriginProtocol/origin-dapp
    branch: ((branch))
    paths: [src/*]
- name: npm-cache
  type: npm-cache
  source:
    <<: *origin-dapp-source
    paths:
      - package.json
      - package-lock.json

jobs:
  - name: install-dependencies
    plan:
      - get: origin-dapp
        trigger: true
      - get: npm-cache
  - name: test
    plan:
      - get: origin-dapp
      - get: npm-cache
        passed: [install-dependencies]
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: 9-alpine
          inputs:
            - name: origin-dapp
            - name: npm-cache
          run:
            path: /bin/sh
            args:
            - -c
            - |
              set -eux
              # Run tests
              cp -r npm-cache/node_modules origin-dapp
              cd origin-dapp && npm run test
  - name: build-and-push
    plan:
      - get: origin-box
      - get: origin-js
      - get: origin-dapp
        passed: [test]
      - task: create monorepo
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: origin-box
            - name: origin-js
            - name: origin-dapp
          outputs:
            - name: origin
          run:
            path: /bin/sh
            args:
            - -c
            - |
              set -eux
              # Create monorepo structure
              # Can't use mv due to mounts
              mkdir -p origin
              cp -r origin-box/* origin
              cp -r origin-dapp origin
              cp -r origin-js origin
      - task: build container
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              # Docker in Docker
              repository: karlkfi/concourse-dcind
          inputs:
            - name: origin
          run:
            path: entrypoint.sh
            args:
              - bash
              - -ceux
              - |
                docker --version
                cd origin
                # Install git for hash retrieval
                apk add git
                export GIT_HASH=`(cd origin-dapp && git rev-parse --short HEAD)`
                echo "Building container for origin-dapp@#${GIT_HASH}"
                docker build . -f deployment/dockerfiles/((environment))/origin-dapp -t ((containerRegistry))gcr.io/origin-214503/((environment))/origin-dapp:${GIT_HASH}
                docker push ((containerRegistry))/((environment))/origin-dapp:${GIT_HASH}
