apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auto-gke-pvc-snapshots
spec:
  schedule: "0 */1 * * *"
  startingDeadlineSeconds: 10800
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: auto-gke-pvc-snapshots
            image: "gcr.io/origin-214503/auto-gke-pvc-snapshots:latest"
          restartPolicy: OnFailure
